version: '3.1'
services:
  adam-kerplank:
    restart: 'always'
    image: 'localhost:5000/adam-kerplank:dev'
    ports:
      - "8907:8080"
    container_name: 'adam-kerplank'
    command: ["java", "-Dfile.encoding=UTF-8", "-jar", "adam-kerplank.jar"]
